### ISSUE TITLE
LaTeX Warning: Label `pgfidxy' multiply defined

### ISSUE THREAD

**Issue by ghost** [Vidabe/tikzsymbols#1]
If I compile a document using these cool symbols and also use \tikzset{every picture/.append style={remember picture}}, then there are warning of the type "Label `pgfidxy' multiply defined". A workaround has been presented [here](https://tex.stackexchange.com/a/412965/121799). However, it might be worthwhile mentioning this workaround in the manual, or to teach Ti*k*Z not to remember the pictures of the package regardless of whether \tikzset{every picture/.append style={remember picture}} has been set.

**Comment by Vidabe** [comment]
I apologize that it took so long for my response, I expected that I would get an E-Mail if a new issue is created (by not-me) and therefore I didn't look.

Thanks for the report! Yeah, I should extend the manual as the "boxes are saved and copied" approach created and creates a lot more problems then I expected. Currently I think I will create two options, one similar to `baseline` (something like `remember-picture=true/false`) and a second option which allows to append styles to the internal `__tikzsymbols` style (so that one doesn't need to look inside the code).

But an update of the documentation is definitely needed.
